version: '3'
services:
    user-service:
        image: 172.16.78.45:5000/enjoyf/user-service-devtest
        environment:
            - SPRING_PROFILES_ACTIVE=devtest,swagger
#            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@eureka-config-server:28761/config
#            - SPRING_DATASOURCE_URL=jdbc:mysql://172.16.78.45:3306/userservice-devtest?useUnicode=true&characterEncoding=utf8&useSSL=false
#            - SPRING_REDIS_HOST = 172.16.78.45
#            - SPRING_REDIS_PORT = 26379
            - LOGBACK_LOGLEVEL = DEBUG
            - JHIPSTER_SLEEP=10
            - JAVA_OPTS=-server -Xmx512m -Xms256m
        deploy:
          replicas: 1
          update_config:
            parallelism: 2
            delay: 10s
          restart_policy:
            condition: on-failure
networks:
  default:
    external:
      name: cloud-devtest


