#-------------------------------------------------------------------------------
# Note for using the rate-limiting:
#   The comment part won't be copied if you use the subgenerator docker-compose
#   you have to manually copy it
#-------------------------------------------------------------------------------
version: '2'
services:
    gateway-server:
        image: 172.16.78.45:5000/enjoyf/gateway-server
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            #- SPRING_DATASOURCE_URL=jdbc:mysql://gatewayserver-mysql:3306/gatewayserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            #- SPRING_DATA_CASSANDRA_CONTACTPOINTS=gatewayserver-cassandra
            - JHIPSTER_SLEEP=20 # gives time for the Cassandra cluster to start and execute the migration scripts
            - JAVA_OPTS=-Xmx512m -Xms256m
        ports:
            - 8888:8888
#    gatewayserver-mysql:
#        extends:
#            file: mysql.yml
#            service: gatewayserver-mysql
    # Uncomment to have Cassandra working with the gateway
    # gatewayserver-cassandra:
    #     extends:
    #         file: cassandra-cluster.yml
    #         service: gatewayserver-cassandra
    # gatewayserver-cassandra-migration:
    #     extends:
    #         file: cassandra-migration.yml
    #         service: gatewayserver-cassandra-migration
    #     environment:
    #         - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
