version: '3'
services:
    gateway-server:
        image: 172.16.78.45:5000/enjoyf/gateway-server-alpha
        environment:
            - SPRING_PROFILES_ACTIVE=alpha,swagger
#            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@eureka-config-server:8761/config
            #- SPRING_DATASOURCE_URL=jdbc:mysql://gatewayserver-mysql:3306/gatewayserver?useUnicode=true&characterEncoding=utf8&useSSL=false
            #- SPRING_DATA_CASSANDRA_CONTACTPOINTS=gatewayserver-cassandra
            - JHIPSTER_SLEEP=5 # gives time for the Cassandra cluster to start and execute the migration scripts
            - JAVA_OPTS=-Xmx512m -Xms256m
#            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@eureka-config-server:8761/eureka/
        ports:
            - 8888:8888
        deploy:
          replicas: 2
          update_config:
            parallelism: 2
            delay: 10s
          restart_policy:
            condition: on-failure
#    jhipster-registry:
#            image: jhipster/jhipster-registry:v2.6.0
#            volumes:
#                - ./central-server-config:/central-config
#            # When run with the "dev" Spring profile, the JHipster Registry will
#            # read the config from the local filesystem (central-server-config directory)
#            # When run with the "prod" Spring profile, it will read the config from a git repository
#            # See http://jhipster.github.io/microservices-architecture/#registry_app_configuration
#            environment:
#                - SPRING_PROFILES_ACTIVE=prod
#                - SECURITY_USER_PASSWORD=admin
#                - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/localhost-config/
#                # - GIT_URI=https://github.com/jhipster/jhipster-registry/
#                # - GIT_SEARCH_PATHS=central-config
#            deploy:
#              replicas: 1
#              update_config:
#                parallelism: 2
#                delay: 0s
#              restart_policy:
#                condition: on-failure
#            ports:
#                - 8761:8761
networks:
  default:
    external:
      name: cloud
