/*
 * userservice API
 * userservice API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.enjoyf.platform.userservice.client.model;

import java.util.Objects;
import com.enjoyf.platform.userservice.client.model.UserAccount;
import com.enjoyf.platform.userservice.client.model.UserLogin;
import com.enjoyf.platform.userservice.client.model.UserProfile;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * AccountDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-08T10:52:24.374+08:00")
public class AccountDTO {
  @SerializedName("id")
  private Long id = null;

  @SerializedName("profileNo")
  private String profileNo = null;

  @SerializedName("tokenValiditySeconds")
  private Long tokenValiditySeconds = null;

  @SerializedName("userAccount")
  private UserAccount userAccount = null;

  @SerializedName("userLogin")
  private UserLogin userLogin = null;

  @SerializedName("userProfile")
  private UserProfile userProfile = null;

  public AccountDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public AccountDTO profileNo(String profileNo) {
    this.profileNo = profileNo;
    return this;
  }

   /**
   * Get profileNo
   * @return profileNo
  **/
  @ApiModelProperty(value = "")
  public String getProfileNo() {
    return profileNo;
  }

  public void setProfileNo(String profileNo) {
    this.profileNo = profileNo;
  }

  public AccountDTO tokenValiditySeconds(Long tokenValiditySeconds) {
    this.tokenValiditySeconds = tokenValiditySeconds;
    return this;
  }

   /**
   * Get tokenValiditySeconds
   * @return tokenValiditySeconds
  **/
  @ApiModelProperty(value = "")
  public Long getTokenValiditySeconds() {
    return tokenValiditySeconds;
  }

  public void setTokenValiditySeconds(Long tokenValiditySeconds) {
    this.tokenValiditySeconds = tokenValiditySeconds;
  }

  public AccountDTO userAccount(UserAccount userAccount) {
    this.userAccount = userAccount;
    return this;
  }

   /**
   * Get userAccount
   * @return userAccount
  **/
  @ApiModelProperty(value = "")
  public UserAccount getUserAccount() {
    return userAccount;
  }

  public void setUserAccount(UserAccount userAccount) {
    this.userAccount = userAccount;
  }

  public AccountDTO userLogin(UserLogin userLogin) {
    this.userLogin = userLogin;
    return this;
  }

   /**
   * Get userLogin
   * @return userLogin
  **/
  @ApiModelProperty(value = "")
  public UserLogin getUserLogin() {
    return userLogin;
  }

  public void setUserLogin(UserLogin userLogin) {
    this.userLogin = userLogin;
  }

  public AccountDTO userProfile(UserProfile userProfile) {
    this.userProfile = userProfile;
    return this;
  }

   /**
   * Get userProfile
   * @return userProfile
  **/
  @ApiModelProperty(value = "")
  public UserProfile getUserProfile() {
    return userProfile;
  }

  public void setUserProfile(UserProfile userProfile) {
    this.userProfile = userProfile;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountDTO accountDTO = (AccountDTO) o;
    return Objects.equals(this.id, accountDTO.id) &&
        Objects.equals(this.profileNo, accountDTO.profileNo) &&
        Objects.equals(this.tokenValiditySeconds, accountDTO.tokenValiditySeconds) &&
        Objects.equals(this.userAccount, accountDTO.userAccount) &&
        Objects.equals(this.userLogin, accountDTO.userLogin) &&
        Objects.equals(this.userProfile, accountDTO.userProfile);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, profileNo, tokenValiditySeconds, userAccount, userLogin, userProfile);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountDTO {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    profileNo: ").append(toIndentedString(profileNo)).append("\n");
    sb.append("    tokenValiditySeconds: ").append(toIndentedString(tokenValiditySeconds)).append("\n");
    sb.append("    userAccount: ").append(toIndentedString(userAccount)).append("\n");
    sb.append("    userLogin: ").append(toIndentedString(userLogin)).append("\n");
    sb.append("    userProfile: ").append(toIndentedString(userProfile)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

