/*
 * userservice API
 * userservice API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.enjoyf.platform.userservice.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LoginVM
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-08T10:52:24.374+08:00")
public class LoginVM {
  @SerializedName("password")
  private String password = null;

  @SerializedName("profileKey")
  private String profileKey = null;

  @SerializedName("rememberMe")
  private Boolean rememberMe = null;

  @SerializedName("username")
  private String username = null;

  @SerializedName("loginDomain")
  private String loginDomain = "mobile";

  public LoginVM password(String password) {
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @ApiModelProperty(required = true, value = "")
  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public LoginVM profileKey(String profileKey) {
    this.profileKey = profileKey;
    return this;
  }

   /**
   * Get profileKey
   * @return profileKey
  **/
  @ApiModelProperty(value = "")
  public String getProfileKey() {
    return profileKey;
  }

  public void setProfileKey(String profileKey) {
    this.profileKey = profileKey;
  }

  public LoginVM rememberMe(Boolean rememberMe) {
    this.rememberMe = rememberMe;
    return this;
  }

   /**
   * Get rememberMe
   * @return rememberMe
  **/
  @ApiModelProperty(value = "")
  public Boolean getRememberMe() {
    return rememberMe;
  }

  public void setRememberMe(Boolean rememberMe) {
    this.rememberMe = rememberMe;
  }

  public LoginVM username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(required = true, value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getLoginDomain() {
    return loginDomain;
  }

  public void setLoginDomain(String loginDomain) {
    this.loginDomain = loginDomain;
  }

  public LoginVM loginDomain(String loginDomain){
    this.loginDomain = loginDomain;
    return this;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginVM loginVM = (LoginVM) o;
    return Objects.equals(this.password, loginVM.password) &&
        Objects.equals(this.profileKey, loginVM.profileKey) &&
        Objects.equals(this.rememberMe, loginVM.rememberMe) &&
            Objects.equals(this.loginDomain, loginVM.loginDomain)  &&
        Objects.equals(this.username, loginVM.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(password, profileKey, rememberMe, username,loginDomain);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginVM {\n");
    
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    profileKey: ").append(toIndentedString(profileKey)).append("\n");
    sb.append("    rememberMe: ").append(toIndentedString(rememberMe)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    loginDomain: ").append(toIndentedString(loginDomain)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

