/*
 * userservice API
 * userservice API documentation
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.enjoyf.platform.userservice.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ProfileCount
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-10T18:40:53.687+08:00")
public class ProfileCount {
    @SerializedName("fans")
    private Integer fans = null;

    @SerializedName("follows")
    private Integer follows = null;

    @SerializedName("profileNo")
    private String profileNo = null;

    public ProfileCount fans(Integer fans) {
        this.fans = fans;
        return this;
    }

    /**
     * Get fans
     * @return fans
     **/
    @ApiModelProperty(value = "")
    public Integer getFans() {
        return fans;
    }

    public void setFans(Integer fans) {
        this.fans = fans;
    }

    public ProfileCount follows(Integer follows) {
        this.follows = follows;
        return this;
    }

    /**
     * Get follows
     * @return follows
     **/
    @ApiModelProperty(value = "")
    public Integer getFollows() {
        return follows;
    }

    public void setFollows(Integer follows) {
        this.follows = follows;
    }

    public ProfileCount profileNo(String profileNo) {
        this.profileNo = profileNo;
        return this;
    }

    /**
     * Get profileNo
     * @return profileNo
     **/
    @ApiModelProperty(value = "")
    public String getProfileNo() {
        return profileNo;
    }

    public void setProfileNo(String profileNo) {
        this.profileNo = profileNo;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProfileCount profileCount = (ProfileCount) o;
        return Objects.equals(this.fans, profileCount.fans) &&
                Objects.equals(this.follows, profileCount.follows) &&
                Objects.equals(this.profileNo, profileCount.profileNo);
    }

    @Override
    public int hashCode() {
        return Objects.hash(fans, follows, profileNo);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ProfileCount {\n");

        sb.append("    fans: ").append(toIndentedString(fans)).append("\n");
        sb.append("    follows: ").append(toIndentedString(follows)).append("\n");
        sb.append("    profileNo: ").append(toIndentedString(profileNo)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

