/*
 * userservice API
 * userservice API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.enjoyf.platform.userservice.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * UserSettings
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-04-08T10:52:24.374+08:00")
public class UserSettings {
  @SerializedName("alarmSettings")
  private String alarmSettings = null;

  @SerializedName("createdIp")
  private String createdIp = null;

  @SerializedName("funcSettings")
  private String funcSettings = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("profileNo")
  private String profileNo = null;

  @SerializedName("updatedIp")
  private String updatedIp = null;

  public UserSettings alarmSettings(String alarmSettings) {
    this.alarmSettings = alarmSettings;
    return this;
  }

   /**
   * Get alarmSettings
   * @return alarmSettings
  **/
  @ApiModelProperty(value = "")
  public String getAlarmSettings() {
    return alarmSettings;
  }

  public void setAlarmSettings(String alarmSettings) {
    this.alarmSettings = alarmSettings;
  }

  public UserSettings createdIp(String createdIp) {
    this.createdIp = createdIp;
    return this;
  }

   /**
   * Get createdIp
   * @return createdIp
  **/
  @ApiModelProperty(value = "")
  public String getCreatedIp() {
    return createdIp;
  }

  public void setCreatedIp(String createdIp) {
    this.createdIp = createdIp;
  }

  public UserSettings funcSettings(String funcSettings) {
    this.funcSettings = funcSettings;
    return this;
  }

   /**
   * Get funcSettings
   * @return funcSettings
  **/
  @ApiModelProperty(value = "")
  public String getFuncSettings() {
    return funcSettings;
  }

  public void setFuncSettings(String funcSettings) {
    this.funcSettings = funcSettings;
  }

  public UserSettings id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public UserSettings profileNo(String profileNo) {
    this.profileNo = profileNo;
    return this;
  }

   /**
   * Get profileNo
   * @return profileNo
  **/
  @ApiModelProperty(required = true, value = "")
  public String getProfileNo() {
    return profileNo;
  }

  public void setProfileNo(String profileNo) {
    this.profileNo = profileNo;
  }

  public UserSettings updatedIp(String updatedIp) {
    this.updatedIp = updatedIp;
    return this;
  }

   /**
   * Get updatedIp
   * @return updatedIp
  **/
  @ApiModelProperty(value = "")
  public String getUpdatedIp() {
    return updatedIp;
  }

  public void setUpdatedIp(String updatedIp) {
    this.updatedIp = updatedIp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserSettings userSettings = (UserSettings) o;
    return Objects.equals(this.alarmSettings, userSettings.alarmSettings) &&
        Objects.equals(this.createdIp, userSettings.createdIp) &&
        Objects.equals(this.funcSettings, userSettings.funcSettings) &&
        Objects.equals(this.id, userSettings.id) &&
        Objects.equals(this.profileNo, userSettings.profileNo) &&
        Objects.equals(this.updatedIp, userSettings.updatedIp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alarmSettings, createdIp, funcSettings, id, profileNo, updatedIp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserSettings {\n");
    
    sb.append("    alarmSettings: ").append(toIndentedString(alarmSettings)).append("\n");
    sb.append("    createdIp: ").append(toIndentedString(createdIp)).append("\n");
    sb.append("    funcSettings: ").append(toIndentedString(funcSettings)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    profileNo: ").append(toIndentedString(profileNo)).append("\n");
    sb.append("    updatedIp: ").append(toIndentedString(updatedIp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

