/*
 * userservice API
 * userservice API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.enjoyf.platform.userservice.client.api;

import com.enjoyf.platform.userservice.client.ApiException;
import com.enjoyf.platform.userservice.client.model.ProfileSummary;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProfileSummaryResourceApi
 */
@Ignore
public class ProfileSummaryResourceApiTest {

    private final ProfileSummaryResourceApi api = new ProfileSummaryResourceApi();

    
    /**
     * createProfileSummary
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProfileSummaryUsingPOSTTest() throws ApiException {
        ProfileSummary profileSummary = null;
        ProfileSummary response = api.createProfileSummaryUsingPOST(profileSummary);

        // TODO: test validations
    }
    
    /**
     * deleteProfileSummary
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteProfileSummaryUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteProfileSummaryUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * getAllProfileSummaries
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllProfileSummariesUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<ProfileSummary> response = api.getAllProfileSummariesUsingGET(page, size, sort);

        // TODO: test validations
    }
    
    /**
     * getProfileSummaryByProfileNo
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProfileSummaryByProfileNoUsingGETTest() throws ApiException {
        String profileNo = null;
        ProfileSummary response = api.getProfileSummaryByProfileNoUsingGET(profileNo);

        // TODO: test validations
    }
    
    /**
     * getProfileSummary
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getProfileSummaryUsingGETTest() throws ApiException {
        Long id = null;
        ProfileSummary response = api.getProfileSummaryUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * updateProfileSummary
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateProfileSummaryUsingPUTTest() throws ApiException {
        ProfileSummary profileSummary = null;
        ProfileSummary response = api.updateProfileSummaryUsingPUT(profileSummary);

        // TODO: test validations
    }
    
}
