/*
 * userservice API
 * userservice API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.enjoyf.platform.userservice.client.api;

import com.enjoyf.platform.userservice.client.ApiException;
import com.enjoyf.platform.userservice.client.model.UserSettings;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserSettingsResourceApi
 */
@Ignore
public class UserSettingsResourceApiTest {

    private final UserSettingsResourceApi api = new UserSettingsResourceApi();

    
    /**
     * createUserSettings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createUserSettingsUsingPOSTTest() throws ApiException {
        UserSettings userSettings = null;
        UserSettings response = api.createUserSettingsUsingPOST(userSettings);

        // TODO: test validations
    }
    
    /**
     * deleteUserSettings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteUserSettingsUsingDELETETest() throws ApiException {
        Long id = null;
        api.deleteUserSettingsUsingDELETE(id);

        // TODO: test validations
    }
    
    /**
     * getAllUserSettings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUserSettingsUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<UserSettings> response = api.getAllUserSettingsUsingGET(page, size, sort);

        // TODO: test validations
    }
    
    /**
     * getUserSettingsByProfileNo
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserSettingsByProfileNoUsingGETTest() throws ApiException {
        String profileNo = null;
        UserSettings response = api.getUserSettingsByProfileNoUsingGET(profileNo);

        // TODO: test validations
    }
    
    /**
     * getUserSettings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserSettingsUsingGETTest() throws ApiException {
        Long id = null;
        UserSettings response = api.getUserSettingsUsingGET(id);

        // TODO: test validations
    }
    
    /**
     * updateUserSettingsByProfileNo
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserSettingsByProfileNoUsingPUTTest() throws ApiException {
        UserSettings userSettings = null;
        UserSettings response = api.updateUserSettingsByProfileNoUsingPUT(userSettings);

        // TODO: test validations
    }
    
    /**
     * updateUserSettings
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserSettingsUsingPUTTest() throws ApiException {
        UserSettings userSettings = null;
        UserSettings response = api.updateUserSettingsUsingPUT(userSettings);

        // TODO: test validations
    }
    
}
