/*
 * userservice API
 * userservice API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.enjoyf.platform.userservice.client.api;

import com.enjoyf.platform.userservice.client.ApiException;
import com.enjoyf.platform.userservice.client.model.UserLogin;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserLoginResourceApi
 */
@Ignore
public class UserLoginResourceApiTest {

    private final UserLoginResourceApi api = new UserLoginResourceApi();


    /**
     * getAllUserLogins
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllUserLoginsUsingGETTest() throws ApiException {
        Integer page = null;
        Integer size = null;
        List<String> sort = null;
        List<UserLogin> response = api.getAllUserLoginsUsingGET(page, size, sort);

        // TODO: test validations
    }

    /**
     * getUserLoginByLoginAndLoginDomain
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserLoginByLoginAndLoginDomainUsingGETTest() throws ApiException {
        String login = null;
        String loginDomain = null;
        UserLogin response = api.getUserLoginByLoginAndLoginDomainUsingGET(login, loginDomain);

        // TODO: test validations
    }

    /**
     * getUserLogin
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getUserLoginUsingGETTest() throws ApiException {
        Long id = null;
        UserLogin response = api.getUserLoginUsingGET(id);

        // TODO: test validations
    }

    /**
     * updateUserLogin
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateUserLoginUsingPUTTest() throws ApiException {
        UserLogin userLogin = null;
        UserLogin response = api.updateUserLoginUsingPUT(userLogin);

        // TODO: test validations
    }

}
