/*
 * userservice API
 * userservice API documentation
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.enjoyf.platform.userservice.client.api;

import com.enjoyf.platform.userservice.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserMobileResourceApi
 */
@Ignore
public class UserMobileResourceApiTest {

    private final UserMobileResourceApi api = new UserMobileResourceApi();

    
    /**
     * mobileExists
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void mobileExistsUsingGETTest() throws ApiException {
        String mobile = null;
        String profilekey = null;
        Boolean response = api.mobileExistsUsingGET(mobile, profilekey);

        // TODO: test validations
    }
    
    /**
     * sendBindCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendBindCodeUsingPUTTest() throws ApiException {
        String mobile = null;
        Boolean response = api.sendBindCodeUsingPUT(mobile);

        // TODO: test validations
    }
    
    /**
     * sendRegisterCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void sendRegisterCodeUsingPUTTest() throws ApiException {
        String mobile = null;
        String profilekey = null;
        Boolean response = api.sendRegisterCodeUsingPUT(mobile, profilekey);

        // TODO: test validations
    }
    
    /**
     * verifyBindCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyBindCodeUsingPOSTTest() throws ApiException {
        String mobile = null;
        String code = null;
        Boolean response = api.verifyBindCodeUsingPOST(mobile, code);

        // TODO: test validations
    }
    
    /**
     * verifyRegisterBindCode
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void verifyRegisterBindCodeUsingGETTest() throws ApiException {
        String mobile = null;
        String code = null;
        Boolean response = api.verifyRegisterBindCodeUsingGET(mobile, code);

        // TODO: test validations
    }
    
}
