#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }

    stage('check java') {
        sh "java -version"
    }
    def pom
    def mavenHome = "/home/td_java/apache-maven-3.3.9/bin"
    stage('clean') {
        dir("./gateway-server"){
            sh "${mavenHome}/mvn -v"
            sh "${mavenHome}/mvn clean"
            pom = readMavenPom file: 'pom.xml'
            print " current version: ${pom.version}"
        }

    }

//    stage('backend tests') {
//        try {
//            sh "mvn test"
//        } catch(err) {
//            throw err
//        } finally {
//            junit '**/target/surefire-reports/TEST-*.xml'
//        }
//    }

    stage('packaging') {
        dir("./gateway-server") {
            echo "****** start mvn package gateway-server ******"
            sh "PHANTOMJS_CDNURL=https://npm.taobao.org/dist/phantomjs /bin/npm install phantomjs --registry=https://registry.npm.taobao.org --no-proxy"
            sh "${mavenHome}/mvn package -Pprod -DskipTests"
            archiveArtifacts artifacts: '**/target/*.war', fingerprint: true
        }
    }


    def dockerImage
    stage('build docker') {
        dir("./gateway-server") {
            echo "****** start build docker image for gateway-server *****"
            sh "cp -R src/main/docker target/"
            sh "cp target/*.war target/docker/"
            dockerImage = docker.build("enjoyf/gateway-server:${pom.version}", 'target/docker')
        }
    }

    stage('publish docker') {
        docker.withRegistry('http://172.16.78.45:5000/') {
            dockerImage.push 'latest'
        }
    }

    stage("start docker") {
        echo   " start docker container "
        dir("./gateway-server/target/docker") {
            sh "chmod +x deployToDocker.sh"
            sh "./deployToDocker.sh"
        }
    }

    stage('Cleanup ') {
        dir("./gateway-server/target/docker") {
            echo 'cleanup none docker images'
            sh "chmod +x cleanUpImages.sh"
            sh "./cleanUpImages.sh"

//            mail body: 'gateway-server project build and deploy successful',
//                 from: 'xxxx@yyyyy.com',
//                 replyTo: 'xxxx@yyyy.com',
//                 subject: 'gateway-server project build and deploy successful',
//                 to: 'yyyyy@yyyy.com'
        }
    }
}
